import Head from "next/head";
import React, { useEffect } from "react";
import Navbar from "./Navbar";
import { useRouter } from "next/navigation";

type Props = {
  title: string;
  children: React.ReactNode;
};

const Layout: React.FC<Props> = ({ title, children }) => {
  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("auth_token_test");
    if (token !== "token1235564994iwerijef8734835jsdjfjsjf8u89945jksmfn") {
      router.push("/login");
    }
  }, [router]);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="container">{children}</div>
      </main>
    </>
  );
};

export default Layout;
